title: Munkhgerel Ankhtuvshin
logo: "/images/logo.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
  MSc in Data Analytics, 2025
  <br><br>
  Bachelor's in Accounting, 2019
  <a href="https://www.linkedin.com/in/munkhgerel-ankhtuvshin-983839183/">View My LinkedIn Profile</a> 
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
